import os
from flask import Flask, jsonify, request
from flask_cors import CORS
from dotenv import load_dotenv
from summarizer import summarize_text

# Load environment variables from .env file
dotenv_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), '.env')
load_dotenv(dotenv_path)

app = Flask(__name__)

# Enable CORS for frontend communication
CORS(app, resources={r"/*": {"origins": "*"}})

# Verify API key is present
GROQ_API_KEY = os.getenv("GROQ_API_KEY")
if not GROQ_API_KEY:
    print("Warning: GROQ_API_KEY is not set in backend/.env")

@app.route("/", methods=["GET"])
def index():
    """
    Root endpoint returning server status.
    """
    return "Backend Running"


@app.route("/api/health", methods=["GET"])
def health_check():
    """
    Simple health check endpoint to verify backend status.
    """
    return jsonify({
        "status": "healthy",
        "message": "Flask backend is running successfully!"
    }), 200

@app.route("/summarize", methods=["POST"])
@app.route("/api/summarize", methods=["POST"])
def summarize():
    """
    Endpoint that accepts text and returns a summary generated by the Groq API.
    """
    data = request.get_json() or {}
    text = data.get("text", "")
    
    if not text or not text.strip():
        return jsonify({"error": "No text provided to summarize."}), 400
        
    try:
        summary = summarize_text(text)
        return jsonify({
            "status": "success",
            "summary": summary
        }), 200
    except ValueError as ve:
        return jsonify({"error": str(ve)}), 400
    except Exception as e:
        return jsonify({"error": str(e)}), 500


if __name__ == "__main__":
    # Load port dynamically (standard for Render and other cloud platforms)
    port = int(os.environ.get("PORT", 5000))
    # Enable debug mode only in development
    is_development = os.getenv("FLASK_ENV", "development") == "development"
    app.run(host="0.0.0.0", port=port, debug=is_development)
